T2D-GENES: PrediXcan Association - Elastic Net (alpha=0.5) 
========================================================


#### Load libraries and define functions

```{r,echo=FALSE}
library("data.table")
library("ggplot2")
qqunif <-  function(p,BH=T,CI=T,FDRthres=0.05,plot=T,title="NULL",...){
    nn = length(p)
    xx =  -log10((1:nn)/(nn+1))
    dat<-cbind(sort(p),1:nn)
    q<-(nn*dat[,1])/dat[,2] # calculate q-values from p-values
    dat<-cbind(dat,q)
    if (min(dat[,3]>FDRthres)) {
        nsnps<-0
    } else {
        nsnps<-round((sum(p<=max(dat[dat[,3]<FDRthres,1]))/nn)*100,4)
    }
    if (plot) {
        plot( xx,  -sort(log10(p)),
        xlab=expression(Expected~~-log[10](italic(p))),
        ylab=expression(Observed~~-log[10](italic(p))),
        cex.lab=1,mgp=c(2,1,0),pch=20, main=title,
        ... )
        if(CI)
        {
            ## create the confidence intervals
            c95 <- rep(0,nn)
            c05 <- rep(0,nn)
            ## the jth order statistic from a
            ## uniform(0,1) sample
            ## has a beta(j,n-j+1) distribution
            ## (Casella & Berger, 2002,
            ## 2nd edition, pg 230, Duxbury)
            ## this portion was posted by anonymous on
            ## http://gettinggeneticsdone.blogspot.com/2009/11/qq-plots-of-p-values-in-r-using-ggplot2.html

            for(i in 1:nn)
            {
                c95[i] <- qbeta(0.95,i,nn-i+1)
                c05[i] <- qbeta(0.05,i,nn-i+1)
            }
            polygon(c(xx, rev(xx)), c(-log10(c95), rev(-log10(c05))),col = "grey", border = NA)
            #    lines(xx,-log10(c95),col='gray')
            #    lines(xx,-log10(c05),col='gray')
        }
        points(xx,  -sort(log10(p)),pch=20)
        #points(xx[dat[,3]<0.05],  -log10(dat[dat[,3]<0.05,1]),pch=20,col="pink")


        y<-max(-log10(p))
        text(0,y,paste(nsnps,"% of Genes have a q-value <= ",FDRthres,sep=""),pos=4)

        #  print(paste(nsnps,"% of SNPs have a q-value <= ",FDRthres,sep=""))
        abline(0,1,col='red')
        if(BH)
        {
            abline(-log10(0.05),1, col='black',lty=2)
            abline(-log10(0.10),1, col='black',lty=3)
            abline(-log10(0.25),1, col='black',lty=4)
            legend('bottomright', c("FDR = 0.05","FDR = 0.10","FDR = 0.25"),
            col=c('black','black','black'),lty=2:4, cex=1)
            abline(h=-log10(0.05/nn),col="blue") ## bonferroni
        }
    } else {
        return(nsnps)
    }
}
```

#### Define directories 

```{r}
assoc.dir <- "/Volumes/im-lab/nas40t2/jason/projects/PrediXmod/PrediXcan/T2D-GENES/assoc/"
wtccc.dir <- paste0(assoc.dir,"WTCCC/")
hs.dir <- paste0(assoc.dir,"HS/")
aj.dir <- paste0(assoc.dir,"AJ/")
aw.dir <- paste0(assoc.dir,"AW/")
ek.dir <- paste0(assoc.dir,"EK/")
es.dir <- paste0(assoc.dir,"ES/")
ua.dir <- paste0(assoc.dir,"UA/")
um.dir <- paste0(assoc.dir,"UM/")
```

#### Tissue lists 

```{r}
tiss.vec <- c("Adipose-Subcutaneous","AdrenalGland","Artery-Coronary","Brain-Cerebellum",
              "Brain-Cortex","Brain-Hypothalamus","Cells-EBV-transformedlymphocytes","Colon-Sigmoid",
              "Colon-Transverse","Liver","Muscle-Skeletal","Nerve-Tibial","Pancreas","WholeBlood",
              "WholeBloodDGN")
f1 <- function(x,y){paste0(x,y)}
file.vec <- sapply(tiss.vec,f1,y="_0.5_assoc.txt")
f2 <- function(dir,tissue){
          filename <- paste0(f1(dir,tissue),"_0.5_assoc.txt")
          df <- data.frame(fread(filename))
          qqunif(df$P.value,title=tissue)
}
f3 <- function(dir,tissue){
          filename <- paste0(f1(dir,tissue),"_0.5_assoc.txt")
          df <- data.frame(fread(filename))
          df.ord <- df[order(df$P.value,decreasing=FALSE),]
          top.genes <- df.ord$Gene[1:100]
          return(top.genes)
}
```

####Create dataframes 

# European 

## WTCCC
```{r}
mydir <- wtccc.dir
sapply(tiss.vec,f2,dir=wtccc.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.wtccc <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.wtccc <- topgenes
plot <- ggplot(count.df.wtccc[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nWTCCC")

plot
topgenes.df[1:10,]
```

## UM
```{r}
mydir <- um.dir
sapply(tiss.vec,f2,dir=um.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.um <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.um <- topgenes
plot <- ggplot(count.df.um[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nUM")

plot
topgenes.df[1:10,]
```

## UA
```{r}
mydir <- ua.dir
sapply(tiss.vec,f2,dir=ua.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.ua <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.ua <- topgenes
plot <- ggplot(count.df.ua[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nUA")

plot
topgenes.df[1:10,]
```

# African-American 

## AJ
```{r}
mydir <- aj.dir
sapply(tiss.vec,f2,dir=aj.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.aj <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.aj <- topgenes
plot <- ggplot(count.df.aj[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nAJ")

plot
topgenes.df[1:10,]
```

## AW
```{r}
mydir <- aw.dir
sapply(tiss.vec,f2,dir=aw.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.aw <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.aw <- topgenes
plot <- ggplot(count.df.aw[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nAW")

plot
topgenes.df[1:10,]
```

# Asian  

## EK
```{r}
mydir <- ek.dir
sapply(tiss.vec,f2,dir=ek.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.ek <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.ek <- topgenes
plot <- ggplot(count.df.ek[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nEK")

plot
topgenes.df[1:10,]
```

## ES
```{r}
mydir <- es.dir
sapply(tiss.vec,f2,dir=es.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.es <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.es <- topgenes
plot <- ggplot(count.df.es[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nES")

plot
topgenes.df[1:10,]
```



## HS
```{r}
mydir <- hs.dir
sapply(tiss.vec,f2,dir=hs.dir)
topgenes.df <- data.frame(sapply(tiss.vec,f3,dir=mydir),stringsAsFactors=FALSE)
topgenes <- as.vector(t(topgenes.df))
count.df <- data.frame(table(topgenes)); count.df$topgenes <- as.character(count.df$topgenes)
count.df.hs <- count.df[order(count.df$Freq,decreasing=TRUE),]
topgenes.hs <- topgenes
plot <- ggplot(count.df.hs[1:20,],aes(x=reorder(topgenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="dodgerblue1",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,15)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,15, by = 1),1)) +
               ylab("Tissue Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues\nHS")

plot
topgenes.df[1:10,]
```

# Top Genes Analyses across Datasets 
```{r fig.width=20, fig.height=8}
TopGenes <-  c(topgenes.hs,topgenes.wtccc,topgenes.ua,topgenes.um,topgenes.ek,
            topgenes.es,topgenes.aj,topgenes.aw)
count.df <- data.frame(table(TopGenes)); count.df$TopGenes <- as.character(count.df$TopGenes)
count.df<- count.df[order(count.df$Freq,decreasing=TRUE),]
plot <- ggplot(count.df[1:50,],aes(x=reorder(TopGenes,-Freq,max),y=Freq)) + 
               geom_bar(stat="identity",fill="maroon",color="Black") + 
               theme_bw() + coord_cartesian(ylim=c(0,30)) + 
               theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 plot.title = element_text(lineheight=2, face="bold")) + 
               theme(axis.text.x=element_text(angle=-30, hjust=0,size=14),panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(),axis.title.x=element_text(size=15,face="bold",vjust=-0.2),
               axis.title.y=element_text(size=16,face="bold",vjust=0.25), panel.grid.major=element_line(size=0.1),
               panel.grid.minor=element_blank(), axis.text.y=element_text(size=15),legend.text=element_text(size=14),
               legend.title=element_text(size=11)) +
               scale_y_continuous(breaks = round(seq(0,30, by = 2),1)) +
               ylab("Total Count") + xlab("Gene") + ggtitle("Top Genes Across Tissues and Cohorts")

plot
write.table(count.df,"/Users/jtorres/Google Drive/Projects/PrediXcan/T2D-GENES/T2DGENES-reports-/EN.assoc.genes",
            sep="\t",row.names=FALSE,quote=FALSE)
```

